INSERT INTO tb_points_of_interest (name, x, y) VALUES ('lanchonete', 27, 12)
INSERT INTO tb_points_of_interest (name, x, y) VALUES ('posto', 31, 18)
INSERT INTO tb_points_of_interest (name, x, y) VALUES ('joalheria', 15, 12)
INSERT INTO tb_points_of_interest (name, x, y) VALUES ('Floricultura', 19, 21)
INSERT INTO tb_points_of_interest (name, x, y) VALUES ('Pub', 12, 8)
INSERT INTO tb_points_of_interest (name, x, y) VALUES ('Supermercado', 23, 6)
INSERT INTO tb_points_of_interest (name, x, y) VALUES ('Churrascaria', 28, 2)